### ISSUE TITLE
[FEATURE] - A recommended selection of Heirloom Items/gear

### ISSUE THREAD

**Issue by kingreboot** [Rycia/azeroth-pilot-reloaded#111]
Something to make it easier to tell what gear to pick instead of me picking randomly. its a small thing that really does not matter. It could also be nice if it was set up as a button that cycles through the gear each time I hit it.

**Comment by NightofStarrs** [comment]
Hello @kingreboot,

This issue will be closed, due to not following the proper format using the 'FEATURE' tag, please recreate or edit your initial post to have the correct format.
