### ISSUE TITLE
BFA Leveling: Alliance

### ISSUE THREAD

**Issue by LunarWolf** [Rycia/azeroth-pilot-reloaded#12]
Started with intro: Brought me back to SW and gave no arrows or QuestList even though I had path directions. Removed the BFA intro and it brought me back to Boralus, but the next waypoint was 10700 yards away and still no quest list and path directions were gone. I will try again when I get to Drust and advise on what I see.

**Comment by deathmessinger** [comment]
I think I know what is happening here.
do you feel comfortable editing addon files?
If so go into APR BFA file open the Toc. and remove the line that says load on demand.
That should fix your issue.
For some reason the sub-addons are not loading as they should and i do not know why yet.
when we figure it out we will re-implement the load on demand.

**Comment by LunarWolf** [comment]
I am willing to give it a shot! I will let you guys know how it goes.

**Comment by LunarWolf** [comment]
So it seems the original issue is fixed, before I could even try death's suggestion. It auto complete the intro for me, like it should have, however the "use flight path" on tiragarde sound ferry master does not auto select where to go. Making a new issue for that and closing this as the original issue is FIXED.
