### ISSUE TITLE
Binding Issue

### ISSUE THREAD

**Issue by Cellanoid** [Rycia/azeroth-pilot-reloaded#13]
Currently getting this error when logging into toons with APR. Seems to be something regarding my bindings? 

Message: Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML: Binding
Time: Tue Nov 1 07:13:15 2022
Count: 1

Message: Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: name
Time: Tue Nov 1 07:13:15 2022
Count: 1
Stack: Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: name

Locals: <none>

Message: Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: header
Time: Tue Nov 1 07:13:15 2022
Count: 1
Stack: Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: header

Locals: <none>

 

Message: Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: category
Time: Tue Nov 1 07:13:15 2022
Count: 1
Stack: Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: category

Locals: <none>

 

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML: Binding
Time: Tue Nov 1 07:13:15 2022
Count: 1
Stack: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML: Binding

Locals: <none>

 

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: name
Time: Tue Nov 1 07:13:15 2022
Count: 1
Stack: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: name

Locals: <none>

 

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: header
Time: Tue Nov 1 07:13:15 2022
Count: 1
Stack: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: header

Locals: <none>

 

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: category
Time: Tue Nov 1 07:13:15 2022
Count: 1
Stack: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: category

Locals: <none>

**Comment by Aegllor** [comment]
It's a known issue. they are working on it. Nothing to do with your bindings if you interpreted keybindings. Its referencing a file that is part of the addon package.

**Comment by deathmessinger** [comment]
download the addon again from here and that should be fixed

**Comment by Cellanoid** [comment]
I just redownloaded from here and still got the same Lua errors.

**Comment by Neogeekmo** [comment]
@Cellanoid Do you still have this problem with the latest version available on Curseforge?
