### ISSUE TITLE
Auto cutscene skip does not always work

### ISSUE THREAD

**Issue by Velsera** [Rycia/azeroth-pilot-reloaded#17]
Title. Unknown reason as to why some cutscenes do not get skipped automatically.

**Comment by Pahonix** [comment]
Which quest did it not work on? We can't troubleshoot "ehhhh sometimes it works and sometimes it doesn't"

**Comment by LunarWolf** [comment]
One I noticed today was the one for The Vindicaar in the Argus Campaign. Not related to leveling, but I did notice it didn't skip for some reason.

**Comment by Pahonix** [comment]
[https://www.wowhead.com/quest=47224/the-vindicaar](https://www.wowhead.com/quest=47224/the-vindicaar)

This quest? There does not appear to be a cutscene for this quest. I watched two of the videos on that wowhead page and neither one of them saw one when going through it.

**Comment by LunarWolf** [comment]
Ok, so I have had 2 more cutscenes in Argus, they are just not skipping any of the cutscenes for "The Assault begins" portions so far. Again they aren't questing related, but might give insight to what OP was talking about.

**Comment by Velsera** [comment]
https://www.wowhead.com/quest=34439/the-battle-of-the-forge

That is the quest in question I encountered. The following cut scene was not skipped.

**Comment by Aegllor** [comment]
There are some "cutscenes" in WoD. Especially in the intro that do not work like regular cutscenes. They are unable to be skipped as a way to introduce you to some of the characters I believe. It's been like that ever since the expansion was released.

**Comment by Rycia** [comment]
As Aegllor stated, some cutscenes aren't skippable via any addons, a lot of the WoD ones especially.

**Comment by LunarWolf** [comment]
> As Aegllor stated, some cutscenes aren't skippable via any addons, a lot of the WoD ones especially.

The ones that I mentioned were skippable, just adding didn't skip it. All of which were legion related(Argus campaign) just incase this pops up again

**Comment by Rycia** [comment]
we'll see, if this pops up again we'll look into it. but some aren't skippable.

**Comment by Velsera** [comment]
The quest I listed has a skippable cut scene, it worked in APP before.
