### ISSUE TITLE
WoD Talador Alliance

### ISSUE THREAD

**Issue by LunarWolf** [Rycia/azeroth-pilot-reloaded#19]
Went to start Talador and it skipped me right to step 4, picking up Quest 34563 "They Quarry Quandary". This quest has a prerequisite quest. I believe steps 1-3 were that quest, but it skipped right over them for me.
![image](https://user-images.githubusercontent.com/4108628/199409902-86816865-5817-43e4-ba4f-79bf9f9d9659.png)

**Comment by deathmessinger** [comment]
It skipped the first three because they were marked complete by Blizz
Green mean you did them Red means you need to do it.
The first quest in Talador guide is to chose the building(Arsenal in this case)
so if you already have the building that is why it skipped it.

**Comment by LunarWolf** [comment]
So I just finished up more digging. If you previously did that quest and did not pick Arsenal, you have to do this quest (https://www.wowhead.com/quest=34909/while-were-in-the-neighborhood) before you can do do Quest 34563 "They Quarry Quandary". I think what happened was, I previously picked something else while doing that quest before using AAP/APR. I don't know if this is even a fixable thing, but if it isn't, then I guess this issue can be closed as not planned. Thanks for your time!

**Comment by Pahonix** [comment]
Right, this is a problem that manifested itself in the AAP code before it was forked to APR. Here is the pinned message that lived in the AAP discord:

Patch 9.1 broke the autopicker for Draenor outposts. So for future reference: 

**Alliance Draenor outpost choices:** 
Gorgrond: Highpass Sparring Arena
Talador: Wrynn Artillery Tower (aka Arsenal)
Spires: Stoktron Brewery

**Horde Draenor outpost choices:**
Gorgrond: Savage Fight Club
Talador: Vol'jin's Arsenal
Spires: Hearthfire Tavern

If you choose the wrong one and AAP points you to an NPC that doesn't have a quest for you, then you can either quest in Talador on your own without AAP or skip Talador by going into the Custom Path screen (/aap > Custom Path) and removing the Talador route by right-clicking it (it will move back under the Shadowlands column). Note: Alliance players should remove both Talador1 and Talador2 routes. AAP should then guide you to the next zone in your list.
