### ISSUE TITLE
Legion routes disappear once you enter the appropriate zone

### ISSUE THREAD

**Issue by davekover** [Rycia/azeroth-pilot-reloaded#21]
When choosing Legion routes, the addon will effectively hide itself once you enter the zone for the route you have selected. This behavior was not occurring for me with Draenor routes. I have not tried vanilla zones.

To repro, be in Dalaran and choose Azsuna as your next zone. APR will show you the step 'Fly to Illidari stand'. After taking the flight path and as soon as you land, the quest list will be empty. The arrow and next steps will also disappear. If you start a flight to Dalaran, as soon as you exit the Azsuna zone, the next steps & arrow UI will re-appear. 

I have also tried the Stormheim route and the same behavior exists.

**Comment by deathmessinger** [comment]
That issue is fixed in the Git version

**Comment by davekover** [comment]
Ok, can confirm that downloading the latest dev branch does fix this issue.
