### ISSUE TITLE
train apprentice ridding playing Demon hunter

### ISSUE THREAD

**Issue by allemar** [Rycia/azeroth-pilot-reloaded#23]
addon is telling me to train apprentice riding in orgrimmar I have master riding trained.

**Comment by Pahonix** [comment]
Known issue. Use /apr skip

AAP dev never figured out how to adjust based on people’s current flight skills so we inherited that problem.

**Comment by deathmessinger** [comment]
I think the fix is in the newest version (if curse ever approves it)

**Comment by allemar** [comment]
ok thank you for getting back to me =).
    On Thursday, November 10, 2022 at 10:33:35 PM CST, deathmessinger ***@***.***> wrote:  
 
 


I think the fix is in the newest version (if curse ever approves it)

**Comment by Neogeekmo** [comment]
After investigation some routes ask to take mount skills either in hardcoded text or with an ID in the table that returns another hardcoded text 
So if we want to fix this bug, we have to remove the calls of texts in the routes and base only on the functions already present which check if the skill is known or not (it adds already one more line in the UI for the current step)
