### ISSUE TITLE
Guide stuck

### ISSUE THREAD

**Issue by VictoriaPaya** [Rycia/azeroth-pilot-reloaded#26]
I can't manage to get pass step 44 in gorgrond. There is no quest to turn in, just quests to accept (which are the following steps). Doesn't matter what I do, reset the guide or whatever, It's stuck telling me to turn in a quest that doesn't exist. 
![image](https://user-images.githubusercontent.com/102537946/201904190-059db7dd-a4e1-48fa-ae76-e4c2626588b0.png)
If there is a button to skip an step, I can't find it.

**Comment by deathmessinger** [comment]
This is not a bug. In the future please ask on the discord for help with things like this.
This is a quest you should have picked up on step 25
if you do /apr reset it should bring you back to the step
but looking at all the green steps after step 44 you may not be able to do it
just do /apr skip and continue on

**Comment by VictoriaPaya** [comment]
Is there any chance that the /apr skip could be added as a button in the addon settings, instead of having to search for written commands outside the game? Thank you.

**Comment by deathmessinger** [comment]
there really is not a place to put a button for that that is easily accessible.
there are only 3 / commands 
/apr 
/apr skip
/apr reset
if you want buttons for them you will have to make macro sorry
