### ISSUE TITLE
Bag slot count issue for auto-sell option

### ISSUE THREAD

**Issue by CloudTekSystems** [Rycia/azeroth-pilot-reloaded#30]
Not sure what the issue is, but I get the following error whenever I have auto-sell enabled and open a vendor:

https://imgur.com/a/0ayYydR

**Comment by Neogeekmo** [comment]
![image](https://user-images.githubusercontent.com/28711160/202288889-2a4b1534-e3e2-4049-b628-a19d8ae554ba.png)

**Comment by Neogeekmo** [comment]
So I managed to reproduce the error once with APR but I don't get the error message after a /reload 
But I had the same error with BagBrother, so I think it's a change on Blizzard API

**Comment by Neogeekmo** [comment]
I confirm WoW has changed the function in their API, we need to readapt the code on our side
https://wowpedia.fandom.com/wiki/Patch_10.0.2/API_changes
