### ISSUE TITLE
Not seeing quest text

### ISSUE THREAD

**Issue by nihil8** [Rycia/azeroth-pilot-reloaded#33]
Hey love that you're updating this add-on. Recently I'm seeing the quest text disappear it shows like the first letter than nothing.

**Comment by socalminstrel** [comment]
I'm also seeing this bug. As soon as Azeroth Auto Pilot is disabled, quest text is visible again. Reproduced with all other addons disabled.

**Comment by adamkrusza** [comment]
I posted this as an issue in the discord as well, I have a screen shot uploaded with the post in the retail-support-horde thread on 11/14/22
![image](https://user-images.githubusercontent.com/71793572/202762255-6a49aa6f-8c74-4dfb-afe0-14df43f07fb4.png)

**Comment by deathmessinger** [comment]
I have not seen this happen and I don't think others on the Dev team have either.
Can you replicate it? If so what are the steps to do so?
It may take some time to find the issue if we don't have it happen or cant replicate it.

**Comment by NightofStarrs** [comment]
This was posted back on 10/27 in the #general channel, https://discord.com/channels/969401465464565791/969402646823833680/1035363879716388905 -- however, there wasn't much that was done to troubleshoot. But appears to be related specifically to APR, disabling it resolved it - when it was the only addon. It appears that some are having the issue, while others are not.

**Comment by adamkrusza** [comment]
I just got a 30 second clip that shows Quest text being normal, turning on the Auto Accept/Auto Turn In, and then Quest text being cut. I can upload the clip on the Discord server if needed as it exceeds the 10MB limit here. Just let me know where I should post it if you need it.

![image](https://user-images.githubusercontent.com/71793572/203187257-3af72c35-1c78-4f2c-8809-32e2795fd352.png)
![image](https://user-images.githubusercontent.com/71793572/203187334-21d109ae-ac90-4d4e-91ae-a8457e97e58a.png)
![image](https://user-images.githubusercontent.com/71793572/203187378-9efcb478-9c71-4bc1-92e3-6c15ab2e4faf.png)
![image](https://user-images.githubusercontent.com/71793572/203187417-9b01418e-2343-466b-9648-0a865f66becb.png)

**Comment by Nigok** [comment]
i have this issue as well but one thing i have managed to fix it was to just reload a bunch of times now i dont know how many times i did reload but after going around turning off and on different expansions/zones for the addon reloading and just going back and forward like that did the trick after some time, one thing i did notice was if you just turn off one expansion/zone made the text be like normal but having everything on got rid of it until you've reloaded a bunch of times

**Comment by NightofStarrs** [comment]
AAP never had this issue, and APR has only 'fixed' parts of the code, and as far as I am aware, we have not done anything related to the Quest Panel (that is displayed to your character), only trying to fix the Gossip and AutoSelect on WoD's Outposts that was broken since 9.1

Can you find which Expansion specifically may be causing it? They load (at this time), on start up/during a reload, until we can find a better way to properly load. The only thing that is really in those Expansion files is related to the actual route that you take through the zone, no other information. So, it's something in APR-Core that is causing it with how the Quest Panel's display text to behave this way.

**Comment by Neogeekmo** [comment]
bug still present in v2.1.6, certainly due to a caching which is not done correctly because of a call of questlog api, not yet found why and how..

I manage to reproduce it but once I reload the same quest the text appears each time

**Comment by Elminster067** [comment]
Message: Interface/AddOns/APR-Core/QuestTest.lua:945: HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'icon' must be a frame
Time: Sun Jan  1 22:01:19 2023
Count: 3
Stack: Interface/AddOns/APR-Core/QuestTest.lua:945: HereBeDragons-Pins-2.0: AddWorldMapIconMap: 'icon' must be a frame
[string "=[C]"]: ?
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/APR-Core/lib/HereBeDragons/HereBeDragons-Pins-2.0.lua"]:701: in function `AddWorldMapIconMap'
[string "@Interface/AddOns/APR-Core/QuestTest.lua"]:945: in function `MapOrderNumbers'
[string "@Interface/AddOns/APR-Core/QuestTest.lua"]:962: in function <Interface/AddOns/APR-Core/QuestTest.lua:957>

Locals:

**Comment by Elminster067** [comment]
![WoWScrnShot_010123_214959](https://user-images.githubusercontent.com/119313387/210192374-ad47fb26-b9a5-45dd-b391-e8ba1847bea4.jpg)
I opened the quest order list on the mod and click show quest order list and now the quest are showing the texts in them but i keep getting the above error code every time i open the blizzard quest box

**Comment by brainwurks** [comment]
For me it seemed to be related to whether my All The Things window was open. If I reload the ui many times, it also sometimes fixes it until I instance in or out.
![image](https://user-images.githubusercontent.com/121996458/210699632-e0faa386-1c9b-4866-a74d-f6d6850666d4.png)
