### ISSUE TITLE
Dependency Missing  - APR-Core

### ISSUE THREAD

**Issue by Darkjuju666** [Rycia/azeroth-pilot-reloaded#35]
Can't understand why I can't load APR in game, I've installed/reinstalled & installed many times and when I go to game it nothing comes up.

if I type the shortcut /apr (get message help)

if I go to add-on before loading character and hover mouse over the APR it says missing dependcrfies APR-Core

how can I fix this.

Also noite im running on a iMac

**Comment by deathmessinger** [comment]
Ok i know nothing about Mac but I'm going to take a shot in the dark here.
Did you download from Git? if so did you remove all the folders from azeroth-pilot-reloaded-dev folder?
In you addon folder you should have 11 different folders labeled apr-core and apr-(the different expacs)

**Comment by Darkjuju666** [comment]
Hi thanks for your reply,

Thanks for replying I have downloaded the Git folder (also downloaded straight from curse forge) and I have checked that inside the add-on folder there's indeed 11 different apr as you can see below.

<img width="429" alt="Screenshot 2022-11-19 at 15 26 17" src="https://user-images.githubusercontent.com/118612737/202855731-5464bd22-6248-41b3-b391-1696fa0615de.png">

also I've included a screen shot when I check the add-on inside the game

<img width="1111" alt="Screenshot 2022-11-19 at 15 31 11" src="https://user-images.githubusercontent.com/118612737/202855927-96877b71-22ee-439d-990e-c60aedee1bfa.png">

**Comment by deathmessinger** [comment]
ok click the load out of date addons and you should be golden

**Comment by Darkjuju666** [comment]
Thank you so much... it now working
