### ISSUE TITLE
Stuck in the same path with no way of changing.

### ISSUE THREAD

**Issue by Simbaded** [Rycia/azeroth-pilot-reloaded#36]
So, As soon as I installed APR, I was pretty happy to see it work immediatly, the path was already taking me to Draenor ! I was pretty suprised by the fact it asked me to start in Nagrand, but I followed it anyway. Everything worked great ! Felt just like AAP ! 

The issue I have is that one I returned the "Reglakk's Research" quest, the add-on just stopped showing me a path. I've tried reloading it, uninstalling it, changing character... Whatever I seem to do, whatever my character's level, whatever Chromie timeline I choose it always asks me to go back to Nagrand to do the same quests.

Is there anyway I can fix this ?
![APR](https://user-images.githubusercontent.com/118591199/202863514-c7dffd88-0bc7-49f6-990a-a41976de5aee.PNG)

**Comment by Pahonix** [comment]
This is a known issue. Go into /apr > Custom Path. Right-click all the routes under the left Custom Path column to remove them (note which routes are there first). Then right-click them again to return them to the Custom Path column. This should put the routes into the correct order. APR is supposed to do the top most route first.

We have fixed this issue and the fix should be pushed in the next version that is sent to Curseforge.
