### ISSUE TITLE
starting in exile's reach not showing anything

### ISSUE THREAD

**Issue by Nigok** [Rycia/azeroth-pilot-reloaded#53]
i just started a new character brand new name never used before and whatnot and no matter what i choose, custom path with only exile's reach and the speedrun path it does not give me any quests on the list whatsoever for exile's reach and even now with custom path exclusively with exile's reach onits just telling me to go and train riding and pick up a quest in orgrimmar, there is just no path functioning for exile's reach it seems (this is even after getting off the boat and onto the island itself)

**Comment by NightofStarrs** [comment]
Hi @Nigok, can you confirm the version you're on in APR? We just pushed v1.6.4 today. You may need to remove all APR files and re-download as well.

**Comment by Nigok** [comment]
i can confirm that i am on the latest version, i just got this addon probably 5 minutes before i made the post after i saw the comment on AAP that this addon was made

**Comment by NightofStarrs** [comment]
Thank you for checking, I just confirmed that there was a fix made to the Exiles Reach route, and it wasn't properly pushed. It was, but then accidentally got removed before it was fully updated. Looking into this further.

**Comment by NightofStarrs** [comment]
@Nigok, can you remove the APR files in your Interface folder, and click the green '<> Code' button on the main GH page, and download via a ZIP -- then replace them in your Interface folder.

This should fix your problem, and should be pushed to CF at a later time.

**Comment by Nigok** [comment]
alright that fixed it, thank you!
