### ISSUE TITLE
Gilneas quest skip (WIP - Silverpine Forest ) 

### ISSUE THREAD

**Issue by Samerious** [Rycia/azeroth-pilot-reloaded#55]
After accepting the three quests from the north section of Gilneas, APR skips all remaining quests in Gilneas, and directs you to report to Sylvannas at The Forsaken Front. If you follow this, you will go to the Forsaken Front and the proper NPCs will not be there. To progress through this path you need to find Godfrey's body with one of the Valkyries, which is done by completing the quest line in Gilneas from start to finish. 

If you skip a head using /apr skip you it will say quest 27472 is missing.

**Comment by Samerious** [comment]
You can see here 

https://github.com/Rycia/azeroth-pilot-reloaded/blob/acd3cb55800aaddf80acb142fcef1f2afaea0b8f/APR-Vanilla/EasternKingdoms_Horde.lua#L1156

That we go from quest [27290 ](https://www.wowhead.com/quest=27290/to-forsaken-forward-command#)to quest 27438 ([The Great Escape](https://www.wowhead.com/quest=27438/the-great-escape#))

**Comment by NightofStarrs** [comment]
If I recall, this is the same ‘old’ route that AAP had buried, that deathmessinger was fixing up. I had redone the whole intro of that route because of that exact issue. I don’t know if I have the steps anymore but can look for them.

**Comment by NightofStarrs** [comment]
Yup, pulled up the old route from AAP, and it is the same one. It is missing quite a few steps, doesn't properly mark some as completed or not, and then also sends you to Hillsbrad to do the Dalaran Crater bit of the quest line, which would require the rotue to be split into 3 distinct sections, Silverpine 1, Hillsbrad, Silverpine 2. We're looking into a way to be able to have this as one distinct route.

**Comment by Neogeekmo** [comment]
Fix with v2.1.2
