### ISSUE TITLE
Interface issue with APR truncated

### ISSUE THREAD

**Issue by Rycia** [Rycia/azeroth-pilot-reloaded#6]
![image](https://user-images.githubusercontent.com/43384589/194389664-708135d0-5759-4fe4-9ce8-61d9c73dee53.png)
The text on this part of the UI is truncated when it shouldn't be after the shift from AAP to APR

**Comment by deathmessinger** [comment]
![image](https://user-images.githubusercontent.com/11321799/194656360-4e84a2f2-5071-4860-87cc-dde98a6bfee1.png)
I think that is something on your end its not doing that to me on retail or PTR
![image](https://user-images.githubusercontent.com/11321799/194657838-6f84edce-5e15-4512-879f-408271db2902.png)

**Comment by Rycia** [comment]
Alright, that's weird. Might be a ElvUI issue because it has a lot of scaling issues, especially with fonts as of current.

**Comment by deathmessinger** [comment]
I'm not sure about that I have Elvui in retail but ptr all i have on is APR

**Comment by Rycia** [comment]
It's a ElvUI inconsistency if using a different font. Closed.
