### ISSUE TITLE
Typo in enUS.lua

### ISSUE THREAD

**Issue by DennisRas** [Rycia/azeroth-pilot-reloaded#68]
I noticed that you're about to use CF translations, but I see no way to edit or suggest an edit on CF:
https://www.curseforge.com/wow/addons/azeroth-pilot-reloaded/localization/languages/92/phrases#426670

The typo is here:
https://github.com/Rycia/azeroth-pilot-reloaded/blob/d8db3e6a63416b12548704d4f5258f12607f16cb/APR-Core/locales/enUS.lua#L10

**Comment by Pahonix** [comment]
Thank you for the report. Fixed internally and will be pushed out in the next release.
