### ISSUE TITLE
Add SL and DF Zone to zone transitions

### ISSUE THREAD

**Issue by Neogeekmo** [Rycia/azeroth-pilot-reloaded#74]
## Describe the problem

Figuring out how the freaking zone transition was/is done to allow the single StoryModeOnly route for SL and DF
That way we can collapse the routes into one for an expansion, and not 4+ each because of the different zones.

### What version of APR are you using? (Stating 'latest' is not useful)
v2.1.1

### Any additional information?
files: 
/Core/Transport.lua
/Core/TransportDB.lua

**Comment by Neogeekmo** [comment]
`-- Dragonflight
    if (APR.ActiveMap == "DF01H-85-Orgrimmar" and APRt_Zone == 1) then
        APRt_Zone = 85
    elseif (APR.ActiveMap == "DF01A-84-Stormwind" and (APRt_Zone == 1978 or APRt_Zone == 2022)) then
        APRt_Zone = 84
    elseif (APR.ActiveMap == "DF02H-1-Durotar" and (APRt_Zone == 1978 or APRt_Zone == 2022)) then
        APRt_Zone = 1
    elseif (APR.ActiveMap == "DF03N-2022-WakingShores" and APRt_Zone == 2023) then
        APRt_Zone = 2022
    elseif (APR.ActiveMap == "DF04-2023-OhnahranPlains" and APRt_Zone == 2024) then
        APRt_Zone = 2023
    elseif (APR.ActiveMap == "DF05-2024-AzureSpan" and APRt_Zone == 2025) then
        APRt_Zone = 2024
    elseif (APR.ActiveMap == "DF06H-2025-Thaldraszus" and (APRt_Zone == 2135 or APRt_Zone == 2090 or APRt_Zone == 2091 or APRt_Zone == 2088 or APRt_Zone == 2089)) then
        APRt_Zone = 2025
    elseif (APR.ActiveMap == "DF06A-2025-Thaldraszus" and (APRt_Zone == 2135 or APRt_Zone == 2090 or APRt_Zone == 2091 or APRt_Zone == 2088 or APRt_Zone == 2089)) then
        APRt_Zone = 2025
    end`

**Comment by Pahonix** [comment]
Routes on the spreadsheet have been updated to add the first step (or two, if needed) to the previous route to allow for the appropriate overlap.

New exports needed for the following tabs:
DF01H-85-Orgrimmar
DF01A-84-Stormwind
DF02H-1-Durotar
DF03N-2022-WakingShores
DF04-2023-OhnahranPlains
DF05-2024-AzureSpan
