### ISSUE TITLE
quest arrow and greens dots not showing up

### ISSUE THREAD

**Issue by Gundam4994** [Rycia/azeroth-pilot-reloaded#8]
first of all thank you for making this addon after aap and im noticing a issue where the green dots and the arrow are no longer present in the UI or mini map figured id let you know

**Comment by Pahonix** [comment]
We need more information. Where is your character? What quest are you on? Horde or alliance? Can you include a screenshot?

**Comment by Gundam4994** [comment]
looks like its a issue with the initial deployment of the addon after you adjust the arrow and move into the appropriate zone the arrow appears back up along with the green dots, I am in icewind drifts and im horde im on the grimfrost hills quest 
![image](https://user-images.githubusercontent.com/116840424/198409934-4ee1905e-2de9-44b0-a953-936dd1132b20.png)
