### ISSUE TITLE
The auto select of the chromie timeline does not work when there is already one

### ISSUE THREAD

**Issue by Neogeekmo** [Rycia/azeroth-pilot-reloaded#87]
Bug from Davixxa 
## Step to reproduce

- select legion
- active the speedrun route
- talk to chromie
- (expected) auto select the right timeline

**Comment by Davixxa** [comment]
Additional information not included in the initial bug report:

The install was fresh - of the addon anyway.

For good measure, though  I don't expect it to matter, as the game isn't even aware that it isn't running under Windows, the game was running under Proton. If I remember correctly, a 7.x Glorious Eggroll build on a mostly up-to-date Arch Linux system, and installed through the CurseForge-compatible build of WowUp (the Linux client - installed through the AUR (Arch User Repository)).

**Comment by Neogeekmo** [comment]
After investigation, impossible to reproduce (alliance and horde) under window (I really don't think it's from the OS, it would mean that blizzard doesn't interpret lua the same way between OS), the automatic selection works well even when another timeline is already selected.

Maybe you just weren't at the right step when talking to chromie. I also confirm that if it's the right step an extra text appears to say which timeline to choose when talking to chromie.
